export const GET_PANICS_REQUEST = "GET_PANICS_REQUEST";
export const GET_PANICS_SUCCESS = "GET_PANICS_SUCCESS";
export const GET_PANICS_FAIL = "GET_PANICS_FAIL";

export const GET_PANIC_DETAILS_REQUEST = "GET_PANIC_DETAILS_REQUEST";
export const GET_PANIC_DETAILS_SUCCESS = "GET_PANIC_DETAILS_SUCCESS";
export const GET_PANIC_DETAILS_FAIL = "GET_PANIC_DETAILS_FAIL";
export const GET_PANIC_DETAILS_RESET = "GET_PANIC_DETAILS_RESET";